title: Lerntagebuch Mike Ritter
author: Mike Ritter
email: felix.lohmeier@fhgr.ch
description: > # this means to ignore newlines
  Ein Lerntagebuch zum Modul BAIN.

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
